---
- name: Provision New Instances
  hosts: all
  gather_facts: false
  become: true

  vars:
    repo_path: "https://github.com/amathoman/OdeToFood"
    app_path: 'C:\Apps'
    app_name: "OdeToFood"

  tasks:

    - name: Stop Application (DotNet)
      win_shell: |
        $p = Get-Process -Name "dotnet"
        $p | Stop-Process -Force

    - name: Install git
      win_chocolatey:
        name: git
        params: '/GitAndUnixToolsOnPath'
        state: present
      tags: pre_install

    - name: Install multiple packages sequentially
      win_chocolatey:
        name: '{{ item }}'
        state: present
      loop:
      - nodejs
      - dotnetcore-sdk
      tags: pre_install

    - name: Create directory structure
      win_file:
        path: "{{ app_path }}" 
        state: directory
      tags: pre_install

    - name: Delete Repo Directory
      win_file:
        path: '{{ app_path }}\{{ app_name }}'
        state: absent   
      tags: pre_install

    - name: clone repository
      win_shell: |
        cd "{{ app_path }}"
        git clone "{{ repo_path }}" 
      tags: pre_install

    - name: Install PSEXEC
      win_chocolatey:
        name: psexec
        state: present
        ignore_checksums: true
      tags: pre_install

    - name: Run PSEXEC (Runs Applciaiton Update via PowerShell)
      win_psexec:
        command: Powershell C:\Apps\OdeToFood\install.ps1
        interactive: yes
        system: yes
      tags: install_app


    - name: Sleep for a minute to allow applciation to come online
      pause:
        minutes: 1

    - name: Check Applciation
      uri:
        url: http://{{ ansible_host }}
      delegate_to: localhost
      become: false
      register: http_status

    - name: Show http_status
      debug:
        msg: "{{ansible_host}}:  APP OK"
      when: http_status.status == 200
     
