---
- name: Provision New Instances
  hosts: all
  gather_facts: false
  become: true

  vars:
    repo_path: "https://github.com/amathoman/OdeToFood"
    app_path: 'C:\Apps'
    app_name: "OdeToFood"

  tasks:

    - name: Stop Application (DotNet)
      win_shell: |
        $p = Get-Process -Name "dotnet"
        $p | Stop-Process -Force


    # - name: Install git
    #   win_chocolatey:
    #     name: git
    #     params: '/GitAndUnixToolsOnPath'
    #     state: present

    # - name: Install multiple packages sequentially
      # win_chocolatey:
      #   name: '{{ item }}'
      #   state: present
      # loop:
      # - nodejs
      # - dotnetcore-sdk

    # - name: Create directory structure
      # win_file:
      #   path: "{{ app_path }}" 
      #   state: directory
        
    - name: Delete Repo Directory
      win_file:
        path: '{{ app_path }}\{{ app_name }}'
        state: absent   

    - name: Clone Repository
      win_shell: |
        cd "{{ app_path }}"
        git clone "{{ repo_path }}" 

    # - name: Run remote PowerShell Script (async)
    #   win_command: start powershell C:\apps\odetofood\update.ps1
    
    - name: Install PSEXEC
      win_chocolatey:
        name: psexec
        state: present
        ignore_checksums: true
  
    - name: Run PSEXEC (Runs Applciaiton Update via PowerShell)
      win_psexec:
        command: Powershell C:\apps\odetofood\update.ps1
        interactive: yes
        system: yes


    - name: Sleep for a minute to allow applciation to come online
      pause:
        minutes: 1

    # - Name: Ensure App is Running
    #   win_shell: |
    #     $p = Get-Process -Name "dotnet"

