
---
- name: Provision New Instances
  hosts: localhost
  gather_facts: true

  vars:
    os_type: "Windows"

  tasks:

    # - name: Create (or update) SQL Server
    #   azure_rm_sqlserver:
    #     resource_group: RHDemo-AU-EAST
    #     name: testsql
    #     location: "Australia East"
    #    #admin_username: 
    #    # admin_password: 

    - name: Create (or update) SQL Database
      azure_rm_sqldatabase:
        resource_group: RHDemo-AU-EAST
        server_name: sqlcrudtest-5961
        name: testdb
        location: "Australia East"