---
- name: Provision New Instances
  hosts: all
  gather_facts: false
  become: true

  tasks:

    # - name: Ensure App is Running
    #   win_shell: |
    #     $AppCheck = Get-Process -Name "dotnet"
    #     write-host $AppCheck
    #     Return $AppCheck 

    #   register: apprunning

    # - name: Applciation Check (Success)
    #   debug:
    #     msg: Applciation is Running
    #   when: apprunning.stderr !== ''

    # - name: Applciation Check (Failure)
    #   debug:
    #     msg: Applciation is Running
    #   when: apprunning.stderr == ''


    - name: Check Applciation
      uri:
        url: http://{{ ansible_host }}
      delegate_to: localhost
      become: false
      register: http_status

    - name: Show http_status
      debug:
        msg: "{{http_status.status}}"
      when: http_status.status == '200'