---
- name: Provision New Instances
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Ensure App is Running
      win_shell: |
        $AppCheck = Get-Process -Name "dotnet"
        write-host $AppCheck
        Return $AppCheck 

      register: apprunning

    - name: Applciation Success
      debug:
        msg: Applciation is Running
      when: apprunning.stdout