---

- name: Windows | Launch instance
  azure_rm_virtualmachine:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    name: "{{ vm_name }}"
    vm_size: "{{ azure_windows_instance_type }}"
    managed_disk_type: "{{ azure_storage_account_type }}"
    admin_username: "{{ azure_admin_user }}"
    admin_password: "{{ azure_admin_pass }}"
    started: True
    os_type: Windows
    state: present
    public_ip_allocation_method: Dynamic
    virtual_network_name: "{{ azure_virtual_network }}"
    subnet_name: "{{ azure_virtual_subnet }}"
    open_ports:
      - 22    # SSH
      - 80
      - 8080
      - 443 
      - 5986  # WinRM secure
      - 5985  # WinRM
      - 3389  # RDP
    tags:
      Name: "{{ vm_name }}{{ item }}"
      os_type: "{{ os_type }}"
      App: WebApp
    image:
      publisher: "{{ azure_win_publisher }}"
      offer: "{{ azure_win_offer }}"
      version: "{{ azure_win_version }}"
      sku: "{{ azure_win_sku }}"
  with_sequence: count={{ vm_count }}
  register: windows1_jobs
  async: 7200
  poll: 0
  when: os_type == 'Windows'



################### Wait for Jobs ###################

- name: Wait for windows instance creation to complete
  async_status: jid="{{ item.ansible_job_id }}"
  register: windows_instances
  until: windows_instances.finished
  retries: 300
  with_items: 
    - "{{ windows1_jobs.results }}"
  when: os_type == 'Windows'


################### Custom VM Extension ###################  

- name: Windows create VM Extension
  azure_rm_virtualmachine_extension:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"    
    name: custom-script
    virtual_machine_name: "{{ item.invocation.module_args.name }}"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    settings: {"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{ lookup('template', 'custom_script.ps1.j2') | b64encode(encoding='utf-16-le') }}"}
    auto_upgrade_minor_version: true
  with_items: "{{ windows_instances.results }}"
  async: 7200
  poll: 0
  when: os_type == 'Windows'
################### Add Hosts ###################

- name: Windows | Add new instance to host group
  add_host:
    hostname: "{{ item.invocation.module_args.tags.Name }}"
    ansible_host: "{{ item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    private_ip:  "{{ item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}"
    ansible_port: "{{ '22' if (windows_ansible_connection is defined and windows_ansible_connection == 'ssh') else '5986' }}"
    ansible_user: "{{ azure_admin_user }}"
    ansible_password: "{{ azure_admin_pass }}"
    ansible_connection: "{{ windows_ansible_connection | default('winrm') }}"
    ansible_shell_type: "cmd"
    ansible_winrm_transport: "credssp"
    ansible_winrm_server_cert_validation: "ignore"
    groups: windows
  with_items: "{{ windows_instances.results }}"  
  when: os_type == 'Windows'

################### Wait for Instances ###################

- name: Windows | Wait for {{ windows_ansible_connection | default('winrm') }} to come up
  wait_for_connection:
  delegate_to: "{{ item }}"
  with_items: "{{ groups['windows'] }}" 
  when: os_type == 'Windows'




